### ISSUE TITLE
Poster missing after running plex-bloat-fix

### ISSUE THREAD

**Issue by cox890** [bullmoose20/Plex-Stuff#14]
Hi, I just ran the plex-bloat-fix.py; it cleaned up some spaces, but now pretty much all the poster is missing, and the poster showed up after doing a full metadata refresh.

**Comment by bullmoose20** [comment]
You must be doing something incorrectly. Without context or a log file, it’s difficult to assess
________________________________
From: ink79 ***@***.***>
Sent: Friday, December 30, 2022 5:37:15 AM
To: bullmoose20/Plex-Stuff ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bullmoose20/Plex-Stuff] Poster missing after running plex-bloat-fix (Issue #14)


Hi, I just ran the plex-bloat-fix.py; it cleaned up some spaces, but now pretty much all the poster is missing, and the poster showed up after doing a full metadata refresh.

**Comment by ink79** [comment]
ubuntu 18, plexinc/pms-docker:1.29.2.6364-6d72b0cf6

```
PLEX_URL=
PLEX_TOKEN=
NOTIFIARR_ENABLED=0
NOTIFIARR_KEY=NOTIFIARR_KEY
DISCORD_CHANNEL=DISCORD_CHANNEL
DELETE=1
RENAME=0
UNDO=0
TMP_DIR=/opt/plex_db_backups/
DIR_PATH=/opt/plex/Library/Application Support/Plex Media Server/Metadata/
TC_PATH=/opt/plex/Library/Application Support/Plex Media Server/Cache/PhotoTranscoder/
DB_PATH=/opt/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/
TC_DEL=0
SLEEP=60
EMPTY_TRASH=0
CLEAN_BUNDLES=0
OPTIMIZE_DB=0
LOG_FILE_ACTIONS=1
```

i have the log file if you want i can provide that

**Comment by bullmoose20** [comment]
1.3.8 was released that should fix this issue.
