### ISSUE TITLE
No module named 'plexapi'

### ISSUE THREAD

**Issue by lyonza** [bullmoose20/Plex-Stuff#15]
I'm getting this error when trying to run plex-bloat-fix.py

> File "C:\Users\lyonz\Documents\plexstuff\plex-bloat-fix.py", line 11, in <module>
    from plexapi.server import PlexServer
ModuleNotFoundError: No module named 'plexapi'

Not sure what I'm missing?

**Comment by bullmoose20** [comment]
Requirements are not installed. Instructions require that you install the requirements.txt

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Chris ***@***.***>
Sent: Monday, January 23, 2023 4:30 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [bullmoose20/Plex-Stuff] No module named 'plexapi' (Issue #15)


I'm getting this error when trying to run plex-bloat-fix.py

File "C:\Users\lyonz\Documents\plexstuff\plex-bloat-fix.py", line 11, in
from plexapi.server import PlexServer
ModuleNotFoundError: No module named 'plexapi'

Not sure what I'm missing?

**Comment by lyonza** [comment]
Thank you for that. I've made sure the requirements.txt was run, system showed it was being installed but when I run the command, I still get the same error.

**Comment by bullmoose20** [comment]
1.3.8 was released
