### ISSUE TITLE
Subflow 'Refresh_browser' wasn't found.

### ISSUE THREAD

**Issue by azuravian** [bullmoose20/Plex-Stuff#19]
Trying to use the PAD flow for No TVDb ID found for TMDb ID.

Copied the file and pasted into PAD, but there appears to be two subflows that aren't created:
Refresh_browser is called 5 times
close_browsers is called once

**Comment by bullmoose20** [comment]
Hmmm…. The sub flows are supposed to be part of the whole pad flow…
________________________________
From: azuravian ***@***.***>
Sent: Saturday, June 10, 2023 1:36:15 AM
To: bullmoose20/Plex-Stuff ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bullmoose20/Plex-Stuff] Subflow 'Refresh_browser' wasn't found. (Issue #19)


Trying to use the PAD flow for No TVDb ID found for TMDb ID.

Copied the file and pasted into PAD, but there appears to be two subflows that aren't created:
Refresh_browser is called 5 times
close_browsers is called once

**Comment by bullmoose20** [comment]
Although…now that I think about it, it probably does not.

Let me see what I can do…
________________________________
From: azuravian ***@***.***>
Sent: Saturday, June 10, 2023 1:36:15 AM
To: bullmoose20/Plex-Stuff ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bullmoose20/Plex-Stuff] Subflow 'Refresh_browser' wasn't found. (Issue #19)


Trying to use the PAD flow for No TVDb ID found for TMDb ID.

Copied the file and pasted into PAD, but there appears to be two subflows that aren't created:
Refresh_browser is called 5 times
close_browsers is called once

**Comment by bullmoose20** [comment]
Fixed

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: Saturday, June 10, 2023 1:36 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [bullmoose20/Plex-Stuff] Subflow 'Refresh_browser' wasn't found. (Issue #19)


Trying to use the PAD flow for No TVDb ID found for TMDb ID.

Copied the file and pasted into PAD, but there appears to be two subflows that aren't created:
Refresh_browser is called 5 times
close_browsers is called once
