### ISSUE TITLE
Unable to paste any PAD scripts which contain a Function

### ISSUE THREAD

**Issue by Dragonsys** [bullmoose20/Plex-Stuff#21]
I have tried all of your PAD flows and any of them which contain a FUNCTION I am not able to paste into PAD. The Subflows which do not contain a FUNCTION paste into PAD fine.

There is no feedback from PAD, so I don't know if it is an issue with PAD or the Flow text or what, but the only reference I found about this issue occurring is here - https://powerusers.microsoft.com/t5/Power-Automate-Desktop/Ability-to-paste-script-within-Power-Automate-Desktop/td-p/2158401

Maybe an issue with the current version of PAD (2.39.306.23341)?

**Comment by bullmoose20** [comment]
Can you ping me on discord in the PMM server and we can troubleshoot it there.
________________________________
From: Dragonsys ***@***.***>
Sent: Sunday, January 21, 2024 1:42:19 PM
To: bullmoose20/Plex-Stuff ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bullmoose20/Plex-Stuff] Unable to paste any PAD scripts which contain a Function (Issue #21)


I have tried all of your PAD flows and any of them which contain a FUNCTION I am not able to paste into PAD. The Subflows which do not contain a FUNCTION paste into PAD fine.

There is no feedback from PAD, so I don't know if it is an issue with PAD or the Flow text or what, but the only reference I found about this issue occurring is here - https://powerusers.microsoft.com/t5/Power-Automate-Desktop/Ability-to-paste-script-within-Power-Automate-Desktop/td-p/2158401

Maybe an issue with the current version of PAD (2.39.306.23341)?

**Comment by bullmoose20** [comment]
dixed
