### ISSUE TITLE
PMM Config & Image changes

### ISSUE THREAD

**Issue by SturmB** [bullmoose20/Plex-Stuff#4]
Good afternoon.

I apologize for creating an issue on this repo when I'm really asking about your Plex Meta Manager repos. I just didn't know of any other way to contact you.

I downloaded a copy of your repo back on March 5th and got it added to my PMM installation. It's been working quite well, but I noticed a couple of minor flaws with it. I finally got around to correcting them today and had no issues doing so. However, I did notice that one issue still remained: The image for the Anime genre was missing.

So I went back to meisnate12's Configs repo to see if there were updates, only to find that your config/image collection was gone from the list! Why was it removed?

In addition, I now see that there are different poster images in your PMM-Images repo (because they are forked from meisnate12's). Did you do a redesign of all the posters in the last few months? Because if I now download just the Anime poster, it will look considerably different from the rest, which I'd rather not have.

Should I just start over? And if so, should I use the configset labeled "PMM" on meisnate12's list? Or what? I'm just confused about these changes and am looking for the best way to move forward from here.

**Comment by bullmoose20** [comment]
> 

Hello there... you can find me on the PMM discord channel. And it was removed because as of 1.17, most of what I did was not going to work anymore. Essentially, my library is now the default PMM one. Hit me up on discord and we can discuss further.

**Comment by SturmB** [comment]
Thank you for the information and especially for the offer of help on Discord, bullmoose. I decided to wipe out the old settings and start mostly anew by following the [directions on the wiki](https://metamanager.wiki/en/latest/home/guides/defaults.html). Looks like it's working great!

I hope things are going well with you. Thanks again, and perhaps we can chat sometime in the future. 😊
